theme: jekyll-theme-cayman
title: "ETL Project"
description: "ETL Pipeline | FHIR | SNOMED | ICD-10 | HL7 v2 | Python"

markdown: kramdown

navigation:
  - title: Home
    url: /
  - title: About
    url: /about
  - title: ETL Pipeline
    url: /etl_pipeline
  - title: Insights
    url: /insights
  - title: Team
    url: /team
  - title: Presentation
    url: /presentation
